[package]
name = "cv"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.47"
ureq = "2.9"
serde_json = "1.0"

[dev-dependencies]
insta = "1.43.2"
assert_cmd = "2.0"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3